name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt

      - name: Shell syntax check
        run: bash -n fedora-cac-setup.sh

      - name: ShellCheck
        run: shellcheck -x fedora-cac-setup.sh

      - name: shfmt (diff only)
        run: shfmt -d -i 2 -bn -ci -sr .

  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
